export const UI = {
  TOGGLE_MENU: 'TOGGLE_MENU'
}

export const AUTH = {
  TOGGLE_AUTH: 'TOGGLE_AUTH',
  AUTH: 'AUTH',
  // GETPROFILE: 'GETPROFILE',
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER'
}

export const ACCOUNT = {
  UPDATE: 'UPDATE',
  SETPROFILEDATA: 'SETPROFILEDATA',
  SETGENERALDATA: 'SETGENERALDATA',
  CREATEBACKUP: 'CREATEBACKUP',
  RESTOREBACKUP: 'RESTOREBACKUP',
  DELETEBACKUP: 'DELETEBACKUP'
}
