var states = [
  {name: 'ALABAMA', id: 'AL'},
  {name: 'ALASKA', id: 'AK'},
  {name: 'AMERICAN SAMOA', id: 'AS'},
  {name: 'ARIZONA', id: 'AZ'},
  {name: 'ARKANSAS', id: 'AR'},
  {name: 'CALIFORNIA', id: 'CA'},
  {name: 'COLORADO', id: 'CO'},
  {name: 'CONNECTICUT', id: 'CT'},
  {name: 'DELAWARE', id: 'DE'},
  {name: 'DISTRICT OF COLUMBIA', id: 'DC'},
  {name: 'FEDERATED STATES OF MICRONESIA', id: 'FM'},
  {name: 'FLORIDA', id: 'FL'},
  {name: 'GEORGIA', id: 'GA'},
  {name: 'GUAM', id: 'GU'},
  {name: 'HAWAII', id: 'HI'},
  {name: 'IDAHO', id: 'ID'},
  {name: 'ILLINOIS', id: 'IL'},
  {name: 'INDIANA', id: 'IN'},
  {name: 'IOWA', id: 'IA'},
  {name: 'KANSAS', id: 'KS'},
  {name: 'KENTUCKY', id: 'KY'},
  {name: 'LOUISIANA', id: 'LA'},
  {name: 'MAINE', id: 'ME'},
  {name: 'MARSHALL ISLANDS', id: 'MH'},
  {name: 'MARYLAND', id: 'MD'},
  {name: 'MASSACHUSETTS', id: 'MA'},
  {name: 'MICHIGAN', id: 'MI'},
  {name: 'MINNESOTA', id: 'MN'},
  {name: 'MISSISSIPPI', id: 'MS'},
  {name: 'MISSOURI', id: 'MO'},
  {name: 'MONTANA', id: 'MT'},
  {name: 'NEBRASKA', id: 'NE'},
  {name: 'NEVADA', id: 'NV'},
  {name: 'NEW HAMPSHIRE', id: 'NH'},
  {name: 'NEW JERSEY', id: 'NJ'},
  {name: 'NEW MEXICO', id: 'NM'},
  {name: 'NEW YORK', id: 'NY'},
  {name: 'NORTH CAROLINA', id: 'NC'},
  {name: 'NORTH DAKOTA', id: 'ND'},
  {name: 'NORTHERN MARIANA ISLANDS', id: 'MP'},
  {name: 'OHIO', id: 'OH'},
  {name: 'OKLAHOMA', id: 'OK'},
  {name: 'OREGON', id: 'OR'},
  {name: 'PALAU', id: 'PW'},
  {name: 'PENNSYLVANIA', id: 'PA'},
  {name: 'PUERTO RICO', id: 'PR'},
  {name: 'RHODE ISLAND', id: 'RI'},
  {name: 'SOUTH CAROLINA', id: 'SC'},
  {name: 'SOUTH DAKOTA', id: 'SD'},
  {name: 'TENNESSEE', id: 'TN'},
  {name: 'TEXAS', id: 'TX'},
  {name: 'UTAH', id: 'UT'},
  {name: 'VERMONT', id: 'VT'},
  {name: 'VIRGIN ISLANDS', id: 'VI'},
  {name: 'VIRGINIA', id: 'VA'},
  {name: 'WASHINGTON', id: 'WA'},
  {name: 'WEST VIRGINIA', id: 'WV'},
  {name: 'WISCONSIN', id: 'WI'},
  {name: 'WYOMING', id: 'WY'}
]

module.exports = states
